version: "3.8"
services:
  client:
    build: ./client
    ports:
      - "8080:80"
    # command: serve -s dist -l 3000
  server:
    build: ./server
    ports:
      - "3005:3005"
    command: npm run start
